# torchtitan Config.toml for NSA 100M model

[job]
dump_folder = "./outputs/nsa_100m"
description = "NSA 100M model training with Native Sparse Attention"
print_args = true
use_for_integration_test = false

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100
enable_memory_snapshot = true
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 10
disable_color_printing = false
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "nsa"
flavor = "100m"
# Use default tokenizer
hf_assets_path = "./tests/assets/tokenizer"
# converters = ["float8"]

# NSA 100M specific parameters
dim = 768
n_layers = 12
n_heads = 12
n_kv_heads = 3  # GQA with 4:1 ratio
vocab_size = 32000
multiple_of = 256
ffn_dim_multiplier = 1.3
norm_eps = 1e-5
rope_theta = 500000.0
max_seq_len = 4096
dropout = 0.0

# NSA specific parameters
compression_block_size = 32
compression_stride = 16
selection_block_size = 64
num_selected_blocks = 16
sliding_window_size = 512

[optimizer]
name = "AdamW"
lr = 3e-4
weight_decay = 0.1
beta1 = 0.9
beta2 = 0.95
eps = 1e-8

[lr_scheduler]
warmup_steps = 2000  # 10% of total steps
decay_ratio = 0.9  # 90% of total steps
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 16
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 20000
dataset = "c4"  # supported datasets: c4_test (2K), c4 (177M)
compile = true

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 1
fsdp_reshard_after_forward = "default"  # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval = 1000
last_save_model_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enabled = true
dataset = "c4_validation"
freq = 500
steps = 100

# A100 specific optimizations
[experimental]
enable_compiled_autograd = false
compiled_autograd_fullgraph = false
compiled_autograd_dynamic = false